### PR TITLE
fix: package don't include module `trino.sqlalchemy`

### LINKED ISSUE #135: ModuleNotFoundError: No module named 'trino.sqlalchemy'
Trying out latest version of `trino==0.308` from PyPy.

Looks like it does not include the `sqlalchemy` module.

Am I being a noob?

### PR DESCRIPTION
**Pull request by dungdm93**
Signed-off-by: Đặng Minh Dũng <dungdm93@live.com>

Fixed #135

### CODE REVIEW

**Comment by dungdm93** [comment]
Demos:
```
$ python setup.py sdist
$ cd dist/
$ tar -tvf trino-0.308.0.tar.gz 
drwxrwxr-x dungdm93/dungdm93 0 2021-12-04 16:03 trino-0.308.0/
-rw-rw-r-- dungdm93/dungdm93 1406 2021-12-04 16:03 trino-0.308.0/PKG-INFO
-rw-rw-r-- dungdm93/dungdm93 6980 2021-12-03 22:24 trino-0.308.0/README.md
-rw-rw-r-- dungdm93/dungdm93  109 2021-12-04 16:03 trino-0.308.0/setup.cfg
-rwxrwxr-x dungdm93/dungdm93 3102 2021-12-04 16:01 trino-0.308.0/setup.py
drwxrwxr-x dungdm93/dungdm93    0 2021-12-04 16:03 trino-0.308.0/trino/
-rw-rw-r-- dungdm93/dungdm93  778 2021-12-03 22:24 trino-0.308.0/trino/__init__.py
-rw-rw-r-- dungdm93/dungdm93 9919 2021-12-03 22:34 trino-0.308.0/trino/auth.py
-rw-rw-r-- dungdm93/dungdm93 20343 2021-12-03 22:24 trino-0.308.0/trino/client.py
-rw-rw-r-- dungdm93/dungdm93  1477 2021-12-03 22:24 trino-0.308.0/trino/constants.py
-rw-rw-r-- dungdm93/dungdm93 17284 2021-12-03 22:24 trino-0.308.0/trino/dbapi.py
-rw-rw-r-- dungdm93/dungdm93  5237 2021-12-03 22:24 trino-0.308.0/trino/exceptions.py
-rw-rw-r-- dungdm93/dungdm93   765 2021-12-03 22:24 trino-0.308.0/trino/logging.py
drwxrwxr-x dungdm93/dungdm93     0 2021-12-04 16:03 trino-0.308.0/trino/sqlalchemy/
-rw-rw-r-- dungdm93/dungdm93   657 2021-12-03 22:24 trino-0.308.0/trino/sqlalchemy/__init__.py
-rw-rw-r-- dungdm93/dungdm93  3203 2021-12-03 22:24 trino-0.308.0/trino/sqlalchemy/compiler.py
-rw-rw-r-- dungdm93/dungdm93  6739 2021-12-03 22:24 trino-0.308.0/trino/sqlalchemy/datatype.py
-rw-rw-r-- dungdm93/dungdm93 12407 2021-12-03 22:24 trino-0.308.0/trino/sqlalchemy/dialect.py
-rw-rw-r-- dungdm93/dungdm93  1058 2021-12-03 22:24 trino-0.308.0/trino/sqlalchemy/error.py
-rw-rw-r-- dungdm93/dungdm93  3429 2021-12-03 22:24 trino-0.308.0/trino/transaction.py
drwxrwxr-x dungdm93/dungdm93     0 2021-12-04 16:03 trino-0.308.0/trino.egg-info/
-rw-rw-r-- dungdm93/dungdm93  1406 2021-12-04 16:03 trino-0.308.0/trino.egg-info/PKG-INFO
-rw-rw-r-- dungdm93/dungdm93   485 2021-12-04 16:03 trino-0.308.0/trino.egg-info/SOURCES.txt
-rw-rw-r-- dungdm93/dungdm93     1 2021-12-04 16:03 trino-0.308.0/trino.egg-info/dependency_links.txt
-rw-rw-r-- dungdm93/dungdm93    69 2021-12-04 16:03 trino-0.308.0/trino.egg-info/entry_points.txt
-rw-rw-r-- dungdm93/dungdm93   199 2021-12-04 16:03 trino-0.308.0/trino.egg-info/requires.txt
-rw-rw-r-- dungdm93/dungdm93     6 2021-12-04 16:03 trino-0.308.0/trino.egg-info/top_level.txt
```

**Comment by hashhar** [comment]
Can you also add something like to `trino/__init__.py` so that sqlalchemy is also available if it's installed?

```python
try:
    from . import sqlalchemy
    __all__ += ['sqlalchemy']
except ImportError:
    import warnings
    warnings.warn('SQLAlchemy integration requires the sqlalchemy extra to be installed, try with '
                  'pip install trino[sqlalchemy]')
```

**Comment by dungdm93** [comment]
@hashhar So dbapi users (don't have `sqlalchemy` package installed) always receive this warning when `import trino`, right?

**Comment by dungdm93** [comment]
@hashhar So this will make dbapi users (don't have `sqlalchemy` package installed) always receive this warning when `import trino`, right?

**Comment by hashhar** [comment]
Ah, good point @dungdm93. I think we should place this warning in `trino/sqlalchemy/__init__.py` instead?

My intention was to raise this warning if users install the trino module but don't have the sqlalchemy extra installed.

**Review by ebyhr — APPROVED** [review]

**Comment by ebyhr** [comment]
@dungdm93 Thanks for your contribution. Could you follow this commit message guideline from next time? 
https://github.com/trinodb/trino-python-client#code-style

**Comment by dungdm93** [comment]
Thanks @ebyhr 
@hashhar, SQLAlchemy users usually use like:
```python
from sqlalchemy import create_engine

engine: Engine = create_engine("trino://localhost:8080/system")
```
So they always make sure sqlalchemy exists first, and secondly, sqlalchemy looking for `sqlalchemy.dialects` in `entry_points` in `setup.py` then load `trino.sqlalchemy.dialect` module directly. So even you put it in `trino/sqlalchemy/__init__.py`, it's not working in most of the cases.

**Pull request merged**
