### PR TITLE
Fix pytz module not found error

### PR DESCRIPTION
**Pull request by aksakalli**
Fixing https://github.com/trinodb/trino-python-client/issues/165 issue.

### CODE REVIEW

**Review by hashhar — COMMENTED** [review]
I'd have expected that the setup.py would have ensured that pytz gets installed as a dependency?

**Comment by aksakalli** [comment]
> I'd have expected that the setup.py would have ensured that pytz gets installed as a dependency?

I thought the intention of https://github.com/trinodb/trino-python-client/pull/160 is to depend on `pytz` only when `experimental_python_types=True`.

**Review by hashhar — DISMISSED** [review]
This seems like the better solution to me.

However you'd still want to add an entry to "extras_require" to setup.py for experimental types support so that pytz gets installed automatically.

The reason why pytz doesn't get installed by default is because `install_requires` in setup.py only lists `requests`.

**Comment by hashhar** [comment]
On second thought, the API allows people to switch between normal and python types on the fly. So ideally pytz must be a required dependency otherwise the code may fail at runtime depending on how the cursor is created.

**Comment by hashhar** [comment]
Alternative solution implemented in #168.

**Pull request closed without merging**
