### PR TITLE
Remove normalize method from TemporalType

### PR DESCRIPTION
**Pull request by hovaesco**
## Description
Remove normalize method from TemporalType.
Related to https://github.com/trinodb/trino-python-client/issues/449

## Release notes

( ) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by hashhar** [comment]
> Resolves https://github.com/trinodb/trino-python-client/issues/449

I don't think this PR does it. It just removes dead code. We're missing tests for values which lie in DST gap or are doubled.

The existing tests for this which were added in the beginning only worked in the timezone of the author, not CI, in CI the session zone is such that those values don't create DST ambiguities.

Please adjust commit message to say something like `This code has been dead/broken since 2b9ca0c2e59496e168907fec1df7a50f26976dce`.

**Review by hashhar — APPROVED** [review]
LGTM % commit message

**Comment by hovaesco** [comment]
Adjusted the commit message.

**Review by hashhar — APPROVED** [review]

**Comment by hashhar** [comment]
please mind ci.

**Review by hashhar — APPROVED** [review]

**Pull request merged**
