### PR TITLE
Remove unused 'redirect_handler' code

### PR DESCRIPTION
**Pull request by Shaheer-rossoneri14**
## Description

In be74586c29f2583c3e62de2a07183ad67857511c the redirect_handler code was removed but only partially.

This change removes the rest of the dead code related to redirect_handler.

## Release notes

(x) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Review by hashhar — APPROVED** [review]
Thank you.

**Comment by hashhar** [comment]
FYI @findepi since you were involved in https://github.com/trinodb/trino-python-client/commit/be74586c29f2583c3e62de2a07183ad67857511c

**Review by hovaesco — APPROVED** [review]

**Comment by hashhar** [comment]
@clabot check

**Comment by hashhar** [comment]
@cla-bot check

**Pull request merged**
