### PR TITLE
Align query cancellation with JDBC driver

### PR DESCRIPTION
**Pull request by mdesmet**
## Description

Align query cancellation with JDBC driver

## Release notes

(x) This is not user-visible or docs only and no release notes are required.
( ) Release notes are required, please propose a release note for me.
( ) Release notes are required, with the following suggested text:

### CODE REVIEW

**Review by hashhar — APPROVED** [review]
Thanks for catching this. This also simplifies things a bit.

For reference of future readers see DELETE on https://trino.io/docs/current/develop/client-protocol.html#http-methods.

**Comment by hashhar** [comment]
I'd just reword commit to say "Fix query cancellation to correctly follow the protocol" since the client indeed didn't follow the documented protocol.

**Review by damian3031 — APPROVED** [review]

**Review by hovaesco — APPROVED** [review]

**Comment by hovaesco** [comment]
It addresses https://github.com/trinodb/trino-python-client/issues/289

**Comment by mdesmet** [comment]
@hashhar : PTAL

**Pull request merged**
