### PR TITLE
Log http response in TrinoQuery#cancel at debug instead of info

### LINKED ISSUE #215: printing http response as info in client.py cancel()
Hi all.

```
[INFO|client.py:807] 2022-08-11 10:01:04,392 > <Response [204]>
```

https://github.com/trinodb/trino-python-client/blame/e26027375326a1e0fc8a472d242af75b4e6049bc/trino/client.py#L807

Is it intended or should it be debug level?

### PR DESCRIPTION
**Pull request by EugeneChung**
Fixes #215

### CODE REVIEW

**Review by hashhar — APPROVED** [review]
Thank you

**Comment by hashhar** [comment]
Can you make the commit more detailed like `Adjust log level to debug in TrinoQuery#cancel`? Makes it easier to avoid confusing that we are globally changing log levels when looking at git log.

**Comment by EugeneChung** [comment]
@hashhar I've changed it.

**Comment by hashhar** [comment]
Thank you!

**Pull request merged**
