### PR TITLE
Add `CertificateAuthentication` class to support cert based authentication

### PR DESCRIPTION
**Pull request by austenLacy**
Add `CertificateAuthentication` class to support cert based authentication.

Re: https://github.com/trinodb/trino-python-client/issues/30

### CODE REVIEW

**Review by ebyhr — APPROVED** [review]
Could you capitalize the commit message? 
`Add CertificateAuthentication class to support cert based authentication`

https://github.com/trinodb/trino-python-client#code-style

**Comment by ebyhr** [comment]
CI hit #156

**Review by hashhar — APPROVED** [review]
LGTM % Yuya's comments.

Thanks.

**Comment by austenLacy** [comment]
> Could you capitalize the commit message? `Add CertificateAuthentication class to support cert based authentication`
> 
> https://github.com/trinodb/trino-python-client#code-style

@ebyhr done ✅

**Comment by hashhar** [comment]
Thank you

**Pull request merged**
